name: "Build and test Nix packages"
on:
  push:
    branches: [main]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v15
        with:
          name: esp32-dev-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix flake check --all-systems
      - run: nix build --override-input nixpkgs github:NixOS/nixpkgs/nixpkgs-unstable github:srid/devour-flake -L --no-link --print-out-paths --override-input flake path:"$GITHUB_WORKSPACE"
      - run: nix-shell -p bash --run "echo OK"
